config/routes.rb
BolsaDeEmpregos::Application.routes.draw do
  root 'dashboard#index'

  concern :accessable do
    get    'login'   => 'sessions#new'
    post   'login'   => 'sessions#create'
    delete 'logout'  => 'sessions#destroy'
  end

  concerns :accessable

  get    'signup'         => 'users#new'
  get    'password/reset' => 'password_reset#edit'
  patch  'password/reset' => 'password_reset#update'

  get    'password/forgot' => 'forgot_password#new', as: :new_forgot_password
  post   'password/forgot' => 'forgot_password#create', as: :create_forgot_password
  get    'password/forgot/:token' => 'forgot_password#edit', as: :edit_forgot_password
  patch   'password/forgot/' => 'forgot_password#update', as: :update_forgot_password

  get 'candidates/:id/dashboard' => 'candidates#dashboard', as: :dashboard_candidate
  get 'entities/:id/dashboard' => 'entities#dashboard', as: :dashboard_entity

  get 'featured' => 'featured#index'
  
  resources :candidates
  resources :entities
  resources :news, only: [:index, :show]
  resources :offers
  resources :interests, only: [:create, :destroy]
  resources :applications, only: [:create, :destroy]

  namespace :backoffice do
    root 'dashboard#index'

    concerns :accessable

    resources :users
    resources :news

    get   'users/:id/change_password' => 'users#edit_password', as: :edit_password
    patch 'users/:id/change_password' => 'users#update_password', as: :update_password
  end
end

app/models/backoffice.rb
class Backoffice < User
  DEFAULT_PASSWORD = '123456'

  has_many :news, dependent: :nullify

  before_validation :set_default_password, on: :create

  private

  def set_default_password
    self.password = DEFAULT_PASSWORD
    self.password_confirmation = DEFAULT_PASSWORD
  end
end

app/models/news.rb
class News < ActiveRecord::Base
  extend Searchable
  include DefaultScope

  belongs_to :user # backoffice

  mount_uploader :image, PhotoUploader

  validates :image, file_size: { less_than: 2.megabytes }
  validates :date, timeliness: { type: :date }, allow_blank: true
  validates :title, :date, :summary, :text, :image, presence: true

  scope :title, ->(title) { where('title ILIKE ?', "%#{title}%") }
  scope :active, -> { where(active: true) }
  scope :featured, -> { where(featured: true, active: true) }
end

app/controllers/backoffice/base_controller.rb
class Backoffice::BaseController < ApplicationController
  layout 'backoffice'

  respond_to :js, :html, only: [:destroy]
  respond_to :html, :json

  before_action :authenticate_backofficer!

  def authenticate_backofficer!
    return if logged_in? && current_user.backoffice?

    redirect_to backoffice_login_path, alert: 'Faça o login como backofficer'
  end
end

app/controllers/backoffice/dashboard_controller.rb
class Backoffice::DashboardController < Backoffice::BaseController
  def index ; end
end

app/controllers/backoffice/news_controller.rb
class Backoffice::NewsController < Backoffice::BaseController
  before_action :set_news, only: [:show, :edit, :update, :destroy]

  def index
    @news = News.by(filter_params).page(params[:page])
  end

  def show
  end

  def new
    @news = News.new
  end

  def edit
  end

  def create
    @news = News.new(news_params)

    flash[:notice] = 'Notícia criada com sucesso' if @news.save

    respond_with @news, location: [:backoffice, @news]
  end

  def update
    flash[:notice] = 'Notícia atualizada com sucesso' if @news.update(news_params)

    respond_with @news, location: [:backoffice, @news]
  end

  def destroy
    @news.destroy

    respond_with @news, location: [:backoffice, @news]
  end

  private

  def set_news
    @news = News.find(params[:id])
  end

  def news_params
    params.require(:news).permit(:title, :date, :summary, :text, :image, :featured, :active, :image_cache)
  end

  def filter_params
    if params[:filter]
      params.require(:filter).permit(:title)
    end
  end
end

app/controllers/backoffice/sessions_controller.rb
class Backoffice::SessionsController < Backoffice::BaseController
  skip_before_filter :authenticate_backofficer!, except: :destroy

  layout 'login'

  def new ; end

  def create
    user = Backoffice.find_by(email: params[:session][:email].downcase)

    if user && user.authenticate(params[:session][:password])
      log_in user

      redirect_to backoffice_root_path, notice: 'Login realizado com sucesso'
    else
      flash.now[:alert] = 'Email/password inválidos'

      render 'new'
    end
  end

  def destroy
    log_out if logged_in?

    redirect_to root_path
  end
end

app/controllers/backoffice/users_controller.rb
class Backoffice::UsersController < Backoffice::BaseController
  before_action :set_user, except: [:index, :new, :create]

  def index
    @users = User.by(filter_params).page(params[:page])
  end

  def new
    @user = Backoffice.new
  end

  def show ; end

  def edit ; end

  def edit_password ; end

  def create
    @user = Backoffice.new(user_params)

    flash[:notice] = 'Utilizador criado com sucesso' if @user.save

    respond_with @user, location: backoffice_user_path(@user)
  end

  def update
    flash[:notice] = 'Utilizador atualizado com sucesso' if @user.update(user_params)

    respond_with @user, location: backoffice_user_path(@user)
  end

  def update_password
    if @user.update(password_params)
      flash[:notice] = 'Password alterada com sucesso'

      redirect_to backoffice_user_path(@user)
    else
      render 'edit_password'
    end
  end

  def destroy
    if current_user.id == params[:id].to_i
      @user.errors.add(:base, :cant_destroy_current_user)
    else
      begin
        @user.destroy
      rescue ActiveRecord::DeleteRestrictionError
        @user.errors.add(:base, :"#{@user.type.underscore}_is_associated_with_applications")
      end
    end

    respond_with @user, location: backoffice_users_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :active)
  end

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end

  def filter_params
    params.require(:filter).permit(:by_name, :type) if params[:filter]
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  load_and_authorize_resource

  def index
    @featured_news = @news.featured.order('RANDOM()').limit(2)

    @news = News.active.where.not(id: @featured_news.pluck(:id)).page(params[:page])
  end

  def show
    @news = News.find(params[:id])
  end
end

app/views/backoffice/news/_form.html.erb
<h1>Inserir/Editar</h1>

<%= simple_form_for [:backoffice, @news] do |f| %>
  <%= f.error_notification %>

  <div class="row">
    <%= f.input :title, wrapper_html: { class: 'col-xs-10' }, input_html: { class: 'form-control' } %>
    <%= f.input :date, as: :datepicker, wrapper_html: { class: 'col-xs-2' }, input_html: { class: 'form-control' } %>
  </div>

  <div class="row">
    <%= f.input :summary, wrapper_html: { class: 'col-xs-12' }, input_html: { class: 'form-control', rows: 5 } %>
  </div>

  <%= tinymce_assets %>

  <div class="row">
    <%= f.input :text, wrapper_html: { class: 'col-xs-12' }, input_html: { class: 'tinymce form-control', rows: 10 } %>
  </div>

  <%= tinymce %>

  <div class="row">
    <%= f.input :image, wrapper_html: { class: 'col-xs-2' }, input_html: { class: 'form-control', input_html: { 'data-max-size' => 2.megabytes } } %>
    <%= f.hidden_field :image_cache %>
  </div>

  <div class="row">
    <%= f.input :featured,  wrapper_html: { class: 'col-xs-2' } %>
    <%= f.input :active, wrapper_html: { class: 'col-xs-2' } %>
  </div>

  <div class="row">
    <%= f.button :submit, class: 'btn btn-success btn-submit', wrapper_html: { class: 'col-xs-2' }, input_html: { class: 'form-control' } %>

    <%= link_to 'Cancelar', :back, class: 'btn btn-default' %>
  </div>
<% end %>

app/views/backoffice/news/_news.html.erb
<tr id="<%= dom_id(news) %>">
  <td><%= truncate news.title, length: 80 %></td>
  <td><%= l news.date %></td>
  <td><%= t news.featured.to_s %></td>
  <td><%= t news.active.to_s %></td>
  <td colspan="3">
    <%= link_to 'Detalhe', [:backoffice, news], class: 'btn btn-default' %>
    <%= link_to 'Editar', [:edit, :backoffice, news], class: 'btn btn-primary' %>
    <%= link_to 'Apagar', [:backoffice, news], class: 'btn btn-danger', data: { method: :delete, remote: true } %>
  </td>
</tr>

app/views/backoffice/news/_search_fields.html.erb
<div class="form-group">
  <%= f.label :title, class: 'sr-only' %>

  <div class="input-group">
    <%= render 'button_search' %>

    <%= f.input_field :title, placeholder: 'Pesquisar' %>
  </div>
</div>

app/views/backoffice/news/destroy.js.erb
$("#<%= dom_id(@news) %>").fadeOut('slow', function() {
  $(this).remove();
});

app/views/backoffice/news/edit.html.erb
<%= render 'form' %>

app/views/backoffice/news/index.html.erb
<h3>Notícias</h3>

<%= render 'search_form', url: backoffice_news_index_path %><br>

<table class="table table-striped table-bordered">
  <thead>
    <th>Notícia</th>
    <th>Data</th>
    <th>Destaque</th>
    <th>Activa</th>
    <th colspan="3">Ações</th>
  </thead>
  <tbody>
    <%= render @news %>
  </tbody>
</table>

<div id="pagination">
  <%= render 'paginate', collection: @news %>
</div>

<%= link_to 'Inserir', new_backoffice_news_path, class: 'btn btn-success' %>

app/views/backoffice/news/index.js.erb
$('tbody').html("<%= escape_javascript(render @news) %>")

$('#pagination').html("<%= escape_javascript(render('paginate', collection: @news)) %>");

app/views/backoffice/news/new.html.erb
<%= render 'form' %>

app/views/backoffice/news/show.html.erb
<h3>Detalhe da Notícia</h3>

<div class="row">
  <div class="col-xs-8">
    <h5>
      <strong>Título</strong><br><br>

      <%= @news.title %>
    </h5>
  </div>

  <div class="col-xs-2">
    <h5>
      <strong>Data</strong><br><br>

      <%= l @news.date %>
    </h5>
  </div>
</div>

<div class="row">
  <div class="col-xs-12">
    <h5><strong>Sumário</strong></h5>

    <p><%= @news.summary %></p>
  </div>
</div>

<div class="row">
  <div class="col-xs-12">
    <h5><strong>Texto</strong></h5>

    <%= @news.text.html_safe %>
  </div>
</div><br>

<div class="row">
  <div class="col-xs-12">
    <h5><strong>Imagem</strong></h5>

    <p><%= image_tag @news.image_url(:medium), class: 'img-rounded' %></p>
  </div>
</div><br>

<div class="row">
  <div class="col-xs-4">
    <h5><strong>Destaque</strong></h5>

    <p><%= t @news.featured.to_s %></p>
  </div>

  <div class="col-xs-4">
    <h5><strong>Activa</strong></h5>

    <p><%= t @news.active.to_s %></p>
  </div>
</div><br>

<div class="row">
  <div class="col-xs-12">
    <%= link_to 'Editar', [:edit, :backoffice, @news], class: 'btn btn-primary' %>
    <%= link_to 'Apagar', [:backoffice, @news], class: 'btn btn-danger', method: :delete, confirm: 'Tens certeza?' %>
    <%= link_to 'Inserir', new_backoffice_news_path, class: 'btn btn-success' %>
    <%= link_to 'Listagem', backoffice_news_index_path, class: 'btn btn-default' %>
  </div>
</div>