config/routes.rb
BolsaDeEmpregos::Application.routes.draw do
  root 'dashboard#index'

  concern :accessable do
    get    'login'   => 'sessions#new'
    post   'login'   => 'sessions#create'
    delete 'logout'  => 'sessions#destroy'
  end

  concerns :accessable

  get    'signup'         => 'users#new'
  get    'password/reset' => 'password_reset#edit'
  patch  'password/reset' => 'password_reset#update'

  get    'password/forgot' => 'forgot_password#new', as: :new_forgot_password
  post   'password/forgot' => 'forgot_password#create', as: :create_forgot_password
  get    'password/forgot/:token' => 'forgot_password#edit', as: :edit_forgot_password
  patch   'password/forgot/' => 'forgot_password#update', as: :update_forgot_password

  get 'candidates/:id/dashboard' => 'candidates#dashboard', as: :dashboard_candidate
  get 'entities/:id/dashboard' => 'entities#dashboard', as: :dashboard_entity

  get 'featured' => 'featured#index'
  
  resources :candidates
  resources :entities
  resources :news, only: [:index, :show]
  resources :offers
  resources :interests, only: [:create, :destroy]
  resources :applications, only: [:create, :destroy]

  namespace :backoffice do
    root 'dashboard#index'

    concerns :accessable

    resources :users
    resources :news

    get   'users/:id/change_password' => 'users#edit_password', as: :edit_password
    patch 'users/:id/change_password' => 'users#update_password', as: :update_password
  end
end

app/models/entity.rb
class Entity < User
  include SharedUserValidations

  has_enumeration_for :professional_activity

  has_many :offers, dependent: :destroy
  has_many :candidates, through: :interests, source: :user
  has_many :interested_candidates, through: :interested, source: :interested

  validates :professional_activity, :nif, presence: true
  validates :nif, length: { is: 9 },
                  numericality: { only_integer: true },
                  uniqueness: true

  scope :professional_activity, ->(value) { where(professional_activity: value) }

  scope :featured, -> do
    most_have_interested_ones.most_have_active_offers
  end

  scope :most_have_active_offers, -> do
    select('users.*, count(offers.entity_id) AS active_offers_count').
    joins(:offers).
    where(offers: { active: true }).
    group('users.id').
    order('active_offers_count DESC')
  end
end

app/controllers/entities/registrations_controller.rb
class Entities::RegistrationsController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :create, :update, :destroy]

  before_action :set_entity, only: [:edit, :show, :update]

  def index
    @entities = Entity.all
  end

  def new
    @entity = Entity.new
  end

  def edit ; end

  def show ; end

  def create
    @entity = Entity.create(entity_params)

    respond_with @entity, location: entities_registration_path(@entity)
  end

  def update
    @entity.update_attributes(entity_params)

    respond_with @entity, location: entities_registration_path(@entity)
  end

  private

  def entity_params
    params.require(:entity).permit(
      :email, :password, :password_confirmation, :name, :address, :zipcode,
      :place, :site, :nif, :professional_activity, :presentation, :contact,
      :other_contact)
  end

  def set_entity
    @entity = Entity.find(params[:id])
  end
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  load_and_authorize_resource

  before_action :set_entity, only: [:dashboard, :edit, :show, :update]

  def index
    @collection = Entity.by(filter_params).page(params[:page])
  end

  def dashboard
    @active_offers = @entity.offers.active
    @inactive_offers = @entity.offers.inactive
  end

  def new
    @entity = Entity.new
  end

  def edit ; end

  def show
    @active_offers = @entity.offers.active
  end

  def create
    @entity = Entity.new(entity_params)

    if @entity.save
      log_in @entity ; flash[:notice] = 'Entidade registada com sucesso'
    end

    respond_with @entity, location: dashboard_entity_path(@entity)
  end

  def update
    if @entity.update_attributes(entity_params.except!(:password, :password_confirmation))
      flash[:notice] = 'Entidade atualizada com sucesso'
    end

    respond_with @entity, location: dashboard_entity_path(@entity)
  end

  private

  def set_entity
    @entity = Entity.find(params[:id])
  end

  def entity_params
    params.require(:entity).permit(
      :email, :password, :password_confirmation, :name, :address, :zipcode,
      :place, :site, :nif, :professional_activity, :presentation, :contact,
      :other_contact, :photo, :photo_cache)
  end

  def filter_params
    if params[:filter]
      params.require(:filter).permit(:query, :professional_activity, :place)
    end
  end
end

app/controllers/entity/registrations_controller.rb
class Entity::RegistrationsController < ApplicationController
  before_action :set_entity, only: [:edit, :show, :update]

  def index
    @entities = Entity.all
  end

  def new
    @entity = Entity.new
  end

  def edit ; end

  def show ; end

  def create
    @entity = Entity.create(entity_params)

    respond_with @entity, location: entity_registration_path(@entity)
  end

  def update
    @entity.update_attributes(entity_params)

    respond_with @entity, location: entity_registration_path(@entity)
  end

  private

  def entity_params
    params.require(:entity).permit(
      :email, :password, :password_confirmation, :name, :address, :zipcode,
      :place, :site, :nif, :professional_activity, :presentation, :contact,
      :other_contact)
  end

  def set_entity
    @entity = Entity.find(params[:id])
  end
end

app/helpers/entities_helper.rb
module EntitiesHelper
  def number_of_active_offers(number)
    pluralize(number, 'oferta activa', 'ofertas activas')
  end
end

app/views/entities/_entity.html.erb
<div class="media col-md-6 entity">
  <div class="media-left">
    <div class="media-left">
      <%= link_to image_tag(entity.photo_url(:thumb), class: 'media-object img-rounded'), entity %>
    </div>
  </div>
  <div class="media-body">
    <h4 class="media-heading">
      <%= link_to entity.name, entity %><br>
    </h4>
    <div class="text-muted"><%= number_of_active_offers(entity.offers.active.size) %></div>

    <%= normalize_html_text entity.presentation %>
  </div>

  <% if display_links %>
    <div class="links">
      <% if can? :read, :entity_interest_buttons %>
        <%= render 'interest_buttons', user_id: entity.id %>
      <% end %>

      <% if can? :update, entity %>
        <%= link_to 'Editar', [:edit, entity], class: 'btn btn-primary btn-sm' %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/entities/_form.html.erb
<%= simple_form_for @entity, defaults: { input_html: { class: 'form-control' } } do |f| %>
  <%= f.error_notification %>

  <%= render 'shared_fields', f: f %>

  <div class="row">
    <%= f.input :nif, wrapper_html: { class: 'col-xs-2' } %>
  </div>

  <div class="row">
    <%= f.input :professional_activity, collection: ProfessionalActivity, wrapper_html: { class: 'col-xs-3' } %>
  </div>

  <%= tinymce_assets %>

  <div class="row">
    <%= f.input :presentation, wrapper_html: { class: 'col-xs-12' }, input_html: { class: 'tinymce', rows: 10 } %>
  </div>

  <%= tinymce %>

  <div class="row">
    <%= f.button :submit, class: 'btn btn-success btn-submit' %>

    <% if @entity.persisted? %>
      <%= link_to 'Cancelar', [:dashboard, @entity], class: 'btn btn-default' %>
    <% end %>
  </div>
<% end %>

app/views/entities/_interested.html.erb
<div class="media">
  <div class="media-left">
    <%= link_to image_tag(entity.photo_url(:thumb), class: 'media-object img-rounded'), entity %>
  </div>
  <div class="media-body">
    <h5 class="media-heading"> <%= link_to entity.name, entity %></h5>

    <%= normalize_html_text entity.presentation %>
  </div>
</div>

app/views/entities/_offers_history.html.erb
<div class="media" id="<%= dom_id(offer) %>">
  <div class="media-left">
    <%= link_to image_tag(offer.photo_url(:thumb), class: 'media-object img-rounded'), offer %>
  </div>

  <div class="media-body">
    <h5 class="media-heading">
      <%= link_to offer.title, offer %><br>
      <%= l offer.start_at %> a <%= l offer.end_at %>
    </h5>

    <%= offer.description.truncate(180) %>
  </div>

  <div class="media-right">
    <%= link_to 'Reativar', '', class: 'btn btn-success media-object', data: { active: false, 'offer-id' => offer.id } %>
  </div>
</div>

app/views/entities/_search_fields.html.erb
<div class="form-group">
  <%= f.label :query, class: 'sr-only' %>

  <div class="input-group">
    <%= render 'button_search' %>

    <%= f.input_field :query, placeholder: 'Pesquisar' %>
  </div>
</div>

<%= f.input :professional_activity, collection: ProfessionalActivity, prompt: 'Área de Atividade' %>
<%= f.input :place, collection: Concelhos, prompt: 'Concelhos' %>

app/views/entities/dashboard.html.erb
<div class="row" id="entity-dashboard">
  <div class="col-xs-6">
    <h3>Ofertas</h3>

    <div id="active-offers">
      <%= render partial: 'dashboard/offer', collection: @active_offers, locals: { display_links: true } %>
    </div>

    <%= link_to 'Inserir Oferta', new_offer_path, class: 'btn btn-success btn-insert' %>

    <h3>Histórico</h3>

    <div id="inactive-offers">
      <%= render partial: 'offers_history', collection: @inactive_offers, as: :offer %>
    </div>
  </div>

  <div class="col-xs-4 col-xs-offset-2 links">
    <h3>Entidade</h3>

    <%= link_to 'Editar Dados', [:edit, @entity], class: 'btn btn-primary' %>
    <%= link_to 'Alterar Password', password_reset_path, class: 'btn btn-warning' %>
  </div>

  <div class="col-xs-4 col-xs-offset-2 interested-candidates">
    <h3>Candidatos interessados</h3>

    <%= render partial: 'candidates/interested', collection: @entity.interested_candidates, as: :candidate %>
  </div>
</div>

<%= render 'templates/entities/dashboard_offer' %>

<%= content_for :javascripts do %>
  <%= javascript_include_tag 'entities/dashboard' %>
<% end %>

app/views/entities/edit.html.erb
<h2>Editar Entidade</h2>

<%= render 'form' %>

app/views/entities/index.html.erb
<h3>Entidades</h3>

<%= render 'search_form', url: entities_path %>

<%= render 'index' %>

app/views/entities/index.js.erb
<%= render 'update_index' %>

app/views/entities/new.html.erb
<h2>Nova Entidade</h2>

<%= render 'form' %>

app/views/entities/show.html.erb
<h2><%= @entity.name %></h2>

<div class="media-left">
  <%= link_to image_tag(@entity.photo_url(:medium), class: 'media-object img-rounded'), @entity %><br>

  <div class="text-center">
    <% if can? :read, :entity_interest_buttons %>
      <%= render 'interest_buttons', user_id: @entity.id %>
    <% end %>

    <% if can? :update, @entity %>
      <p><%= link_to 'Editar', [:edit, @entity], class: 'btn btn-primary btn-sm' %></p>
    <% end %>
  </div>
</div>

<div class="media-body">
  <div class="col-xs-12">
    <p><%= @entity.presentation.html_safe %></p>

    <h4>Actividade Profissional</h4>

    <p><%= @entity.professional_activity_humanize %></p>

    <h4>Morada</h4>

    <address>
      <%= @entity.address %><br>
      <%= @entity.zipcode %><br>
      <%= @entity.place_humanize %>
    </address>

    <h4>Contactos</h4>

    <p>
      <%= @entity.contact %><br>
      <%= @entity.other_contact %><br>
      <%= @entity.email %><br><br>
      <%= link_to @entity.site, @entity.site %>
    </p>
  </div>
</div>

<h3>Ofertas Activas</h3>

<%= render partial: 'offers/offer', collection: @active_offers, locals: { display_links: true } %>

<div class="row">
  <div class="col-md-12">
    <%= link_to 'Ver entidades', entities_path %>
  </div>
</div>