config/routes.rb
BolsaDeEmpregos::Application.routes.draw do
  root 'dashboard#index'

  concern :accessable do
    get    'login'   => 'sessions#new'
    post   'login'   => 'sessions#create'
    delete 'logout'  => 'sessions#destroy'
  end

  concerns :accessable

  get    'signup'         => 'users#new'
  get    'password/reset' => 'password_reset#edit'
  patch  'password/reset' => 'password_reset#update'

  get    'password/forgot' => 'forgot_password#new', as: :new_forgot_password
  post   'password/forgot' => 'forgot_password#create', as: :create_forgot_password
  get    'password/forgot/:token' => 'forgot_password#edit', as: :edit_forgot_password
  patch   'password/forgot/' => 'forgot_password#update', as: :update_forgot_password

  get 'candidates/:id/dashboard' => 'candidates#dashboard', as: :dashboard_candidate
  get 'entities/:id/dashboard' => 'entities#dashboard', as: :dashboard_entity

  get 'featured' => 'featured#index'
  
  resources :candidates
  resources :entities
  resources :news, only: [:index, :show]
  resources :offers
  resources :interests, only: [:create, :destroy]
  resources :applications, only: [:create, :destroy]

  namespace :backoffice do
    root 'dashboard#index'

    concerns :accessable

    resources :users
    resources :news

    get   'users/:id/change_password' => 'users#edit_password', as: :edit_password
    patch 'users/:id/change_password' => 'users#update_password', as: :update_password
  end
end

app/models/application.rb
class Application < ActiveRecord::Base
  belongs_to :offer
  belongs_to :candidate, class_name: 'User'

  validates :offer_id, :candidate_id, presence: true
  validates :offer_id, uniqueness: { scope: :candidate_id }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  respond_to :html, :json, :js

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, alert: I18n.t('flash.forbidden')
  end

  def current_candidate
    return unless current_user.try(:candidate?)

    current_user
  end
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  load_and_authorize_resource

  def create
    offer = Offer.find(application_params[:offer_id])

    application = Application.new(candidate: current_user, offer: offer)

    if application.save
      render json: application, status: :created
    else
      render json: application.errors, status: 422
    end
  end

  def destroy
    application = Application.find(params[:id])

    if application.destroy
      render json: application.offer_id, status: 202
    else
      render json: application.errors
    end
  end

  private

  def application_params
    params.require(:application).permit(:offer_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def normalize_html_text(html, length: 170)
    raw(strip_tags(html.html_safe)[0..length] + ' ...')
  end

  def search_results_message
    content_tag(:div, I18n.t('flash.none_results_found'), class: 'alert alert-info')
  end
end

app/views/application/_application_buttons.html.erb
<% application = current_candidate.try(:has_already_applied_for, offer_id) %>

<% if application.nil?  %>
  <%= link_to 'Candidatar-me', '', class: 'btn btn-success btn-sm application', data: { 'apply' => true, 'offer-id' => offer_id } %>
<% else %>
  <%= link_to 'Remover Candidatura', '', class: 'btn btn-warning btn-sm application', data: { 'application-id' => application.id } %>
<% end %>

app/views/application/_authentication_navbar.html.erb
<% if logged_in? %>
  <% if current_user.backoffice? %>
    <%= link_to current_user.name, backoffice_user_path(current_user), class: 'navbar-link' %> |
  <% else %>
    <%= link_to current_user.name, [:dashboard, current_user], class: 'navbar-link' %> |
  <% end %>
  
  <%= link_to 'Sair', logout_path, method: :delete, class: 'navbar-link' %>
<% else %>
  <%= link_to 'Registar-me', signup_path, class: 'navbar-link' %> |
  <%= link_to 'Login', login_path, class: 'navbar-link' %>
<% end %>

app/views/application/_backoffice_navbar.html.erb
<ul class="navigation" role="navigation">
  <li><%= link_to 'Home', backoffice_root_path %></li> |
  <li><%= link_to 'Utilizadores', backoffice_users_path %></li> |
  <li><%= link_to 'Notícias', backoffice_news_index_path %></li>
</ul>

app/views/application/_button_search.html.erb
<span class="input-group-btn">
  <button class="btn btn-default" type="submit">
    <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
  </button>
</span>

app/views/application/_error_message_template.html.erb
<script id="error-message-template" type="text/x-handeblars-template">
  <span class="help-block">{{msg}}</span>
</script>

app/views/application/_flash_messages.html.erb
<% flash.each do |key, msg| %>
  <div class="alert alert-<%= key %> alert-dismissible" role="<%= key %>">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>

    <%= msg %>
  </div>
<% end %>

app/views/application/_index.html.erb
<div id="collection">
  <%= render partial: @collection.name.underscore, collection: @collection, locals: { display_links: true } %>

  <div class="row">
    <div class="col-xs-12">
      <%= paginate @collection, remote: true %>
    </div>
  </div>
</div>

app/views/application/_interest_buttons.html.erb
<% interest = current_user.try(:already_interested_in, user_id) %>

<% if interest.nil? %>
  <%= link_to 'Interessado/a', '', class: 'btn btn-success btn-sm', data: { 'interested' => false, 'user-id' => user_id } %>
<% else %>
  <%= link_to 'Remover Interesse', '', class: 'btn btn-warning btn-sm', data: { 'interested' => interest.id } %>
<% end %>

app/views/application/_navbar.html.erb
<ul class="navigation" role="navigation">
  <li><%= link_to 'Home', root_path %></li> |
  <li><%= link_to 'Entidades', entities_path %></li> |
  <li><%= link_to 'Candidatos', candidates_path %></li> |
  <li><%= link_to 'Ofertas', offers_path %></li> |
  <li><%= link_to 'Destaques', featured_path %></li> |
  <li><%= link_to 'Notícias', news_index_path %></li>
</ul>

app/views/application/_paginate.html.erb
<div class="row">
  <div class="col-xs-12">
    <%= paginate collection, remote: true %>
  </div>
</div>

app/views/application/_search_form.html.erb
<%= simple_form_for :filter, url: url, method: :get, html: { class: 'form-inline' },
    defaults: { input_html: { class: 'form-control' },
    wrapper_html: { class: 'form-group' },
    label_html: { class: 'sr-only' } },
    remote: true do |f| %>
  <%= render 'search_fields', f: f %>
<% end %>

app/views/application/_session_form.html.erb
<div id="login">
  <%= simple_form_for(:session, url: url) do |f| %>
    <%= f.error_notification %>

    <div class="row">
      <%= f.input :email, class: 'form-control', wrapper_html: { class: 'col-xs-4 col-xs-offset-4' }  %>
    </div>

    <div class="row">
      <%= f.input :password, class: 'form-control', wrapper_html: { class: 'col-xs-4 col-xs-offset-4' } %>
    </div>

    <div class="row">
      <div class="col-xs-4 col-xs-offset-6">
        <%= f.submit "Log in", class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>

  <br />

  <div class="row">
    <div class="col-xs-4 col-xs-offset-4">
      <p><%= link_to "Registar-me", signup_path %> | <%= link_to 'Esqueci-me da password', new_forgot_password_path %></p>
    </div>
  </div>
</div>

app/views/application/_shared_fields.html.erb
<div class="row">
  <%= f.input :email, wrapper_html: { class: 'col-xs-6' } %>
</div>

<% if f.object.new_record? %>
  <div class="row">
    <%= f.input :password, wrapper_html: { class: 'col-xs-6' } %>
    <%= f.input :password_confirmation, wrapper_html: { class: 'col-xs-6' } %>
  </div>
<% end %>

<div class="row">
  <%= f.input :name, wrapper_html: { class: 'col-xs-6' } %>
  <%= f.input :photo, wrapper_html: { class: 'col-xs-6'}, input_html: { 'data-max-size' => 1.megabyte } %>
  <%= f.hidden_field :photo_cache %>
</div>

<div class="row">
  <%= f.input :address, wrapper_html: { class: 'col-xs-12' }, input_html: { rows: 5 } %>
</div>

<div class="row">
  <%= f.input :zipcode, wrapper_html: { class: 'col-xs-2' }, input_html: { 'data-mask' => '0000-000', placeholder: '9999-999' } %>
  <%= f.input :place, collection: Concelhos, wrapper_html: { class: 'col-xs-6 col-xs-offset-4' } %>
</div>

<div class="row">
  <%= f.input :contact, wrapper_html: { class: 'col-xs-2' }, input_html: { placeholder: '(+999) 999 999 999'} %>
  <%= f.input :other_contact, wrapper_html: { class: 'col-xs-2' }, input_html: { placeholder: '(99) 999 999 999' }, label_html: { class: 'invisible' } %>
  <%= f.input :site, wrapper_html: { class: 'col-xs-6 col-xs-offset-2' }, input_html: { placeholder: 'http://' } %>
</div>

<%= render 'error_message_template' %>

app/views/application/_update_index.js.erb
$('#collection').html("<%= j(render(partial: @collection.name.underscore, collection: @collection, locals: { display_links: true }) || search_results_message) %>").append("<%= j(render('paginate', collection: @collection)) %>");